import stylistic from '@stylistic/eslint-plugin';
import sonar from 'eslint-plugin-sonarjs';
import jsonc from 'eslint-plugin-jsonc';
import jsdoc from 'eslint-plugin-jsdoc';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import unicorn from 'eslint-plugin-unicorn';
import importPlugin from 'eslint-plugin-import';

// @ts-expect-error - No type declarations
import nounsanitized from 'eslint-plugin-no-unsanitized';

export default [
  {
    ignores: ['dist/**', 'node_modules/**'],
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        project: './tsconfig.json'
      }
    },
    settings: {
      'import/resolver': {
        node: {
          extensions: ['.js', '.jsx', '.ts', '.tsx', '.mjs', '.cjs'],
          moduleDirectory: ['node_modules', 'src'],
        },
        typescript: {
          alwaysTryTypes: true,
          project: './tsconfig.json',
        },
      },
    },
    plugins: {
      '@stylistic': stylistic,
      'sonarjs': sonar,
      'jsonc': jsonc,
      'no-unsanitized': nounsanitized,
      'jsdoc': jsdoc,
      '@typescript-eslint': tsPlugin,
      'unicorn': unicorn,
      'import': importPlugin,
    },
    rules: {
      // Core rules
      'accessor-pairs': ['error', {getWithoutSet: false, setWithoutGet: true, enforceForClassMembers: true}],
      'arrow-body-style': ['error', 'as-needed'],
      'camelcase': ['error'],
      'capitalized-comments': ['error', 'always', {ignoreInlineComments: true, ignoreConsecutiveComments: true}],
      'curly': ['error', 'all'],
      'default-case-last': 'error',
      'dot-notation': 'error',
      'eqeqeq': 'error',
      'func-names': ['error', 'always'],
      'guard-for-in': 'error',
      'no-case-declarations': 'error',
      'no-console': 'error',
      'no-const-assign': 'error',
      'no-constant-condition': 'off',
      'no-fallthrough': 'error',
      'no-global-assign': 'error',
      'no-irregular-whitespace': 'error',
      'no-param-reassign': 'off',
      'no-prototype-builtins': 'error',
      'no-restricted-globals': ['error', 'event', 'origin', 'parent', 'length'],
      'no-undef': 'off',
      'no-undefined': 'error',
      'no-underscore-dangle': ['error', {allowAfterThis: true, allowAfterSuper: false, allowAfterThisConstructor: false}],
      'no-unexpected-multiline': 'error',
      'no-unneeded-ternary': 'error',
      'no-unused-vars': 'off',
      'no-unused-expressions': 'error',
      'no-var': 'error',
      'prefer-const': ['error', {destructuring: 'all'}],
      'require-atomic-updates': 'off',

      // Stylistic rules
      '@stylistic/array-bracket-spacing': ['error', 'never'],
      '@stylistic/arrow-parens': ['error', 'always'],
      '@stylistic/arrow-spacing': ['error', {before: true, after: true}],
      '@stylistic/block-spacing': ['error', 'always'],
      '@stylistic/brace-style': ['error', '1tbs', {allowSingleLine: true}],
      '@stylistic/comma-dangle': ['error', 'always-multiline'],
      '@stylistic/comma-spacing': ['error', {before: false, after: true}],
      '@stylistic/computed-property-spacing': ['error', 'never'],
      '@stylistic/function-call-spacing': ['error', 'never'],
      '@stylistic/function-paren-newline': ['error', 'multiline-arguments'],
      '@stylistic/generator-star-spacing': ['error', 'before'],
      '@stylistic/indent': ['error', 2, {
        SwitchCase: 1,
        MemberExpression: 1,
        flatTernaryExpressions: true,
        ignoredNodes: ['ConditionalExpression'],
      }],
      '@stylistic/key-spacing': ['error', {beforeColon: false, afterColon: true, mode: 'strict'}],
      '@stylistic/keyword-spacing': ['error', {before: true, after: true}],
      '@stylistic/lines-between-class-members': ['error', {enforce: [{blankLine: 'always', prev: 'field', next: 'method'}]}],
      '@stylistic/max-statements-per-line': ['error', {max: 2, ignoredNodes: ['BreakStatement']}],
      '@stylistic/member-delimiter-style': ['error', {
        multiline: {
          delimiter: 'semi',
          requireLast: true,
        },
        singleline: {
          delimiter: 'comma',
          requireLast: false,
        },
        multilineDetection: 'brackets',
      }],
      '@stylistic/new-parens': 'error',
      '@stylistic/no-extra-semi': 'error',
      '@stylistic/no-floating-decimal': 'error',
      '@stylistic/no-multi-spaces': 'error',
      '@stylistic/no-multiple-empty-lines': ['error', {max: 1, maxEOF: 0, maxBOF: 0}],
      '@stylistic/no-tabs': 'error',
      '@stylistic/no-trailing-spaces': 'error',
      '@stylistic/no-whitespace-before-property': 'error',
      '@stylistic/object-curly-newline': 'error',
      '@stylistic/object-curly-spacing': ['error', 'never'],
      '@stylistic/operator-linebreak': ['error', 'after', {overrides: {'|': 'before'}}],
      '@stylistic/padded-blocks': ['error', 'never'],
      '@stylistic/quote-props': ['error', 'consistent-as-needed'],
      '@stylistic/quotes': ['error', 'single', {avoidEscape: true}],
      '@stylistic/rest-spread-spacing': ['error', 'never'],
      '@stylistic/semi': ['error', 'always'],
      '@stylistic/semi-spacing': ['error', {before: false, after: true}],
      '@stylistic/space-before-blocks': 'error',
      '@stylistic/space-before-function-paren': ['error', {anonymous: 'never', named: 'never', asyncArrow: 'always'}],
      '@stylistic/space-in-parens': ['error', 'never'],
      '@stylistic/space-infix-ops': ['error'],
      '@stylistic/space-unary-ops': 'error',
      '@stylistic/spaced-comment': ['error', 'always'],
      '@stylistic/switch-colon-spacing': ['error', {after: true, before: false}],
      '@stylistic/template-curly-spacing': ['error', 'never'],
      '@stylistic/template-tag-spacing': ['error', 'never'],
      '@stylistic/type-annotation-spacing': ['error'],
      '@stylistic/type-generic-spacing': ['error'],
      '@stylistic/type-named-tuple-spacing': ['error'],
      '@stylistic/wrap-iife': ['error', 'inside'],

      // SonarJS rules
      'sonarjs/cognitive-complexity': 'off',
      'sonarjs/no-duplicate-string': 'off',
      'sonarjs/no-empty-test-file': 'off',
      'sonarjs/no-ignored-exceptions': 'off',
      'sonarjs/no-nested-conditional': 'off',
      'sonarjs/no-nested-switch': 'error',
      'sonarjs/no-selector-parameter': 'off',
      'sonarjs/no-small-switch': 'error',
      'sonarjs/todo-tag': 'off',

      // Jsonc rules
      'jsonc/indent': ['error', 2],
      'jsonc/array-bracket-newline': ['error', 'consistent'],
      'jsonc/array-bracket-spacing': ['error', 'never'],
      'jsonc/array-element-newline': ['error', 'consistent'],
      'jsonc/comma-style': ['error', 'last'],
      'jsonc/key-spacing': ['error', {beforeColon: false, afterColon: true, mode: 'strict'}],
      'jsonc/no-octal-escape': 'error',
      'jsonc/object-curly-newline': ['error', {consistent: true}],
      'jsonc/object-curly-spacing': ['error', 'never'],
      'jsonc/object-property-newline': ['error', {allowAllPropertiesOnSameLine: true}],

      // No-unsanitized rules
      'no-unsanitized/method': 'error',
      'no-unsanitized/property': 'error',

      // JSDoc rules
      'jsdoc/check-access': 'error',
      'jsdoc/check-alignment': 'error',
      'jsdoc/check-line-alignment': ['error', 'never', {wrapIndent: '  '}],
      'jsdoc/check-param-names': 'error',
      'jsdoc/check-property-names': 'error',
      'jsdoc/check-tag-names': 'error',
      'jsdoc/check-types': 'error',
      'jsdoc/check-values': 'error',
      'jsdoc/empty-tags': 'error',
      'jsdoc/implements-on-classes': 'error',
      'jsdoc/multiline-blocks': 'error',
      'jsdoc/no-bad-blocks': 'error',
      'jsdoc/no-multi-asterisks': 'error',
      'jsdoc/require-asterisk-prefix': 'error',
      'jsdoc/require-hyphen-before-param-description': ['error', 'never'],
      'jsdoc/require-jsdoc': 'off',
      'jsdoc/require-description': 'off',
      'jsdoc/require-param': 'error',
      'jsdoc/require-param-description': 'off',
      'jsdoc/require-param-name': 'error',
      'jsdoc/require-param-type': 'off',
      'jsdoc/require-property': 'error',
      'jsdoc/require-property-description': 'off',
      'jsdoc/require-property-name': 'error',
      'jsdoc/require-property-type': 'off',
      'jsdoc/require-returns': 'off',
      'jsdoc/require-returns-check': 'error',
      'jsdoc/require-returns-description': 'off',
      'jsdoc/require-returns-type': 'off',
      'jsdoc/require-throws': 'off',
      'jsdoc/require-yields': 'error',
      'jsdoc/require-yields-check': 'error',
      'jsdoc/tag-lines': ['error', 'never', {startLines: 0}],
      'jsdoc/valid-types': 'error',

      // Typescript rules
      '@typescript-eslint/ban-ts-comment': ['error', {'ts-expect-error': {descriptionFormat: '^ - .+$'}}],
      '@typescript-eslint/consistent-type-definitions': ['error', 'type'],
      '@typescript-eslint/explicit-function-return-type': 'error',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-invalid-void-type': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/no-unnecessary-type-arguments': 'off',
      '@typescript-eslint/no-unnecessary-type-conversion': 'error',
      '@typescript-eslint/no-unnecessary-type-parameters': 'off',
      '@typescript-eslint/no-unused-vars': ['error', {vars: 'all', args: 'after-used', argsIgnorePattern: '^_', caughtErrors: 'none'}],
      '@typescript-eslint/parameter-properties': ['error', {prefer: 'parameter-property'}],
      '@typescript-eslint/prefer-readonly': 'error',
      '@typescript-eslint/require-await': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',

      // Typescript core override rules
      'default-param-last': 'off',
      'no-invalid-this': 'off',
      'no-loop-func': 'off',
      'no-shadow': 'off',

      '@typescript-eslint/default-param-last': 'error',
      '@typescript-eslint/no-invalid-this': 'error',
      '@typescript-eslint/no-loop-func': 'error',
      '@typescript-eslint/no-shadow': ['error', {builtinGlobals: false}],

      // Unicorn rules
      'unicorn/consistent-destructuring': 'off',
      'unicorn/consistent-existence-index-check': 'off',
      'unicorn/consistent-function-scoping': 'off',
      'unicorn/escape-case': 'off',
      'unicorn/filename-case': ['error', {case: 'kebabCase'}],
      'unicorn/import-style': 'off',
      'unicorn/no-for-loop': 'off',
      'unicorn/no-hex-escape': 'off',
      'unicorn/no-negated-condition': 'off',
      'unicorn/no-null': 'off',
      'unicorn/no-typeof-undefined': 'off',
      'unicorn/number-literal-case': 'off',
      'unicorn/numeric-separators-style': 'off',
      'unicorn/prefer-at': 'off',
      'unicorn/prefer-code-point': 'off',
      'unicorn/prefer-dom-node-append': 'off',
      'unicorn/prefer-dom-node-remove': 'off',
      'unicorn/prefer-event-target': 'off',
      'unicorn/prefer-global-this': 'off',
      'unicorn/prefer-optional-catch-binding': 'error',
      'unicorn/prefer-query-selector': 'off',
      'unicorn/prefer-string-raw': 'off',
      'unicorn/prefer-string-replace-all': 'off',
      'unicorn/prefer-string-slice': 'error',
      'unicorn/prefer-top-level-await': 'off',
      'unicorn/prefer-type-error': 'off',
      'unicorn/prevent-abbreviations': ['error', {ignore: ['args', '[ijkxyz]', '[sS]earchParams', '[tT]emp', 'dev']}],
      'unicorn/switch-case-braces': 'off',

      // Import rules
      'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],
      'import/extensions': ['error', 'never', {
        js: 'ignorePackages',
        mjs: 'ignorePackages',
      }],
      'import/first': 'error',
      'import/newline-after-import': ['error', {count: 1, exactCount: true, considerComments: true}],
      'import/no-absolute-path': 'error',
      'import/no-cycle': 'error',
      'import/no-duplicates': 'error',
      'import/no-dynamic-require': 'error',
      'import/no-mutable-exports': 'error',
      'import/no-self-import': 'error',
      'import/no-unresolved': 'error',
      'import/no-useless-path-segments': 'error',
      'import/order': ['error', {
        groups: [['builtin', 'external'], 'parent', 'sibling', 'index'],
        alphabetize: {
          order: 'asc',
          orderImportKind: 'asc',
          caseInsensitive: true,
        },
      }],
    }
  }
];
